import {defineConfig} from "@anio-software/enkore"
import {defineTargetOptions} from "@anio-software/enkore.target-js-node"
import {defineAutogeneratedFile} from "@anio-software/enkore"

type AutogeneratedFile = ReturnType<typeof defineAutogeneratedFile>

const subPackages = [
	"copy",
	"file",
	"is",
	"mkdir",
	"path-type",
	"remove",
	"resolve",
	"scandir",
	"stat-path",
	"tmp"
]

const autogeneratedFiles: AutogeneratedFile[] = []

for (const pkg of subPackages) {
	autogeneratedFiles.push(
		defineAutogeneratedFile({
			destinationPath: `project/export/${pkg}/__aggregatedExports.ts`,
			generator() {
				return `export * from "@anio-software/pkg.node-fs-${pkg}"\n`
			}
		})
	)
}

export const config: unknown = defineConfig({
	target: {
		name: "js-node",
		options: defineTargetOptions({
			registry: {
				"anioSoftware": {
					url: "https://npm-registry.anio.software",
					authTokenFilePath: "secrets/anio_npm_auth_token",
					clientPrivateKeyFilePath: "secrets/npm_client.pkey",
					clientCertificateFilePath: "secrets/npm_client.cert"
				}
			},

			packageSourceRegistryByScope: {
				"@anio-software": {
					registry: "anioSoftware"
				}
			},

			publish: [{
				registry: "anioSoftware"
			}]
		})
	},

	autogeneratedFiles
})
